# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: "sample-project-1-240000:asia-northeast1:polls-instance"

runtime_config:
  python_version: 3
# [END runtime]
